name: Build and Deploy
on:
  push:
    branches: main

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby blog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.3.0

      - name: Install Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18.14.0'

      - name: Install Dependencies
        run: npm i --omit=dev

      - name: Build
        run: npm run build

      - name: Upload to S3
        run: aws s3 sync ./public s3://somenugget.dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'

      - name: Create cloudfront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${AWS_DISTRIBUTION_ID} --paths "/*" >> /dev/null
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
          AWS_DEFAULT_REGION: 'eu-west-1'

      - name: Verify build
        run: ls -la public
